apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: sentry
  namespace: epirius
spec:
  parentRefs:
    - name: gke-gateway
      namespace: gateway
  hostnames:
    - sentry.s9n.no
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sentry-nginx
          port: 80
