apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sentry
    repo: https://sentry-kubernetes.github.io/charts
    releaseName: sentry
    namespace: epirius
resources:
  - http-route.yaml